library(tidyr)
library(dplyr)
library(ggplot2)
library(shiny)
library(skimr)
library(psych)
library(reshape2)
library(gridExtra)
library(data.table)
library(GA)
library(ggplot2)
library(data.table)
library(stringi)

setwd("d:/2_granty_projekty/2_Bezici/0_DS/datbaze_data/")
srcDTA =  read.csv(file = "runoff_sediment_intervals_20240917.csv",sep = ";",fileEncoding = "UTF-8")
nrow(srcDTA)
crop_counts <- as.matrix(table(srcDTA$crop))
xx =  subset(srcDTA, is.na(srcDTA$BBCH))
nrow(xx)
BBCH_counts <- as.matrix(table(srcDTA$BBCH))
